[package]
name = "disasm"
description = "Disassembler library"
version = "0.3.1"
license = "LGPL-3.0-only"
keywords = ["disassembler", "decodetree"]
authors = ["Denis Drakhnia <numas13@gmail.com>"]
repository = "https://github.com/numas13/disasm"
edition = "2021"
rust-version = "1.61"

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-unknown-linux-gnu"

[features]
default = ["std"]
std = []
print = ["mnemonic"]
mnemonic = []

# architectures
riscv = []
all-arch = [
    "riscv",
]

[build-dependencies]
decodetree = { version = "0.4.0", features = ["gen"] }
